### ISSUE TITLE
ngx_stream_module.so loaded too late in nginx.conf

### ISSUE THREAD

**Issue by serge-vk** [osokin/nginx-devel#1]
Hello there,
I am reporting this here on the advice of @defanator after submitting an issue to https://github.com/leev/ngx_http_geoip2_module/issues/42. It appears that although dynamic stream modules require loading `ngx_stream_module.so` *before* any of them, in the default `nginx.conf`, the 

```load_module /usr/local/libexec/nginx/ngx_stream_module.so;```

ends up loaded after other stream modules. In my case, it was `geoip2` module, that was placed above and so gave the reported error. I am not sure whether this is a bug, but I never stumbled upon it anywhere that the load sequence was important for stream modules and therefore never thought of modifying it. It was @defanator who put me on the right track.

Thank you.

**Comment by osokin** [comment]
Hi Serge,

thanks for the report.

That's true, the sequence of the modules in nginx.conf is very important.  After conversation with the vendor I've removed a code from Makefile what generates that part of the configuration file.
So, now a customer is always responsible to have a corrected order of modules in the nginx.conf.
